"""Generate solver-free manuscript tables and figures from the frozen cohort."""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / "docs/evidence/sprint_c_final_20260920"
MANUSCRIPT = ROOT / "manuscript"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def render_tables(cases: list[dict], stages: list[dict]) -> str:
    """Keep every attempt and never substitute no-incumbent defaults for results."""
    if len(cases) != 13 or len({r["name"] for r in cases}) != 13:
        raise ValueError("The frozen comparison must contain thirteen unique attempts")
    gurobi = [r for r in cases if r["backend"] == "Gurobi"]
    scip = [r for r in cases if r["backend"] == "SCIP"]
    if len(gurobi) != 7 or len(scip) != 6:
        raise ValueError("Unexpected solver cohort")
    if any(r["incumbent_available"] for r in scip):
        raise ValueError("New SCIP evidence requires a new editorial assessment")
    lines = [
        "<!-- Generated by scripts/build_manuscript_comparison.py; do not edit. -->",
        "",
        "| Hubs / arcs / profile | Outcome | Capacity gap (%) | Economic gap (%) | "
        "Optimization (h) | RSS (GiB) |",
        "|:--|:--|--:|--:|--:|--:|",
    ]

    def label(row):
        route = "D" if row["direct_arcs"] else "W"
        method = "B" if "all_barrier" in row["name"] else "A"
        return f"{row['warehouses']} / {route} / {method}"

    def percentage(value):
        return "—" if value is None else f"{100 * value:.4f}"

    for row in gurobi:
        outcome = "Certified" if row["outcome"] == "quality_certified" else "Uncertified"
        gaps = row["stage_gaps"]
        lines.append(
            f"| {label(row)} | {outcome} | {percentage(gaps['emergency_capacity'])} | "
            f"{percentage(gaps.get('economic_cost'))} | {row['optimization_seconds'] / 3600:.3f} | "
            f"{row['application_peak_rss_gib']:.2f} |"
        )
    lines += [
        "",
        ": Gurobi attempts. W: warehouse-only; D: direct-enabled; A: historical",
        "automatic profile; B: all-barrier. Gaps belong to the respective passes.",
        "An em dash denotes an unexecuted economic pass. All seven incumbents",
        "passed their original independent validation. RSS is the application",
        "process high-water mark, not the configured memory limit. {#tbl-gurobi-comparison}",
        "",
        "| Hubs / arcs | Internal limit (MB) | Termination | Optimization (h) | RSS (GiB) |",
        "|:--|--:|:--|--:|--:|",
    ]
    for row in scip:
        route = "D" if row["direct_arcs"] else "W"
        limit = row["solver_config"]["solver_options"]["limits/memory"]
        stop = "Memory limit" if row["outcome"].startswith("mem_") else "Time limit"
        lines.append(
            f"| {row['warehouses']} / {route} | {limit} | {stop} | "
            f"{row['optimization_seconds'] / 3600:.3f} | {row['application_peak_rss_gib']:.2f} |"
        )
    lines += [
        "",
        ": SCIP/SoPlex attempts. Every attempt terminated without an incumbent;",
        "economic cost, achieved service and a finite gap are therefore unavailable.",
        "The 393216 MB repeats also used larger nodes and allocations.",
        "Times include the application optimization region. {#tbl-scip-comparison}",
        "",
        "![Optimization time and application peak RSS for all thirteen attempts. "
        "Bar colours distinguish quality-certified solutions, valid uncertified incumbents "
        "and no-incumbent outcomes; this is not a paired speedup estimate.]"
        "(figures/solver-comparison.png){#fig-solver-comparison}",
        "",
        "| Hubs / arcs / profile | Economic cost (billion input-currency units) | "
        "Final static score (million) | Final reception overflow (million t) |",
        "|:--|--:|--:|--:|",
    ]
    for row in gurobi:
        if row["outcome"] == "quality_certified":
            lines.append(
                f"| {label(row)} | {row['economic_cost'] / 1e9:.3f} | "
                f"{row['emergency_static_capacity'] / 1e6:.3f} | "
                f"{row['emergency_reception_capacity'] / 1e6:.3f} |"
            )
    lines += [
        "",
        ": Conditional outputs of quality-certified Gurobi attempts. The static",
        "score sums scenario-weighted stock exceedances over warehouse-periods;",
        "it is not installed capacity. Reception overflow is already a period",
        "quantity. Costs exclude artificial penalties and do not identify a",
        "causal benefit of direct arcs under differing inherited limits. "
        "{#tbl-economic-observations}",
        "",
        "| Hubs / arcs / profile | Service (s) | Capacity (s) | Economics (s) |",
        "|:--|--:|--:|--:|",
    ]
    for row in gurobi:
        measured = {
            s["stage_role"]: s["runtime_seconds"] for s in stages if s["name"] == row["name"]
        }
        values = [
            f"{measured[role]:.1f}" if role in measured else "—"
            for role in ("unmet_demand", "emergency_capacity", "economic_cost")
        ]
        lines.append(f"| {label(row)} | " + " | ".join(values) + " |")
    lines += [
        "",
        ": Native Gurobi pass runtimes. These are not primary optimization times",
        "for an entire job, and their sum need not equal the enclosing application",
        "timer. Time-limited passes can slightly exceed the nominal remaining",
        "budget while returning control. {#tbl-stage-times}",
        "",
    ]
    return "\n".join(lines)


def pipeline_figure(destination: Path) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.patches import FancyArrowPatch, FancyBboxPatch

    fig, ax = plt.subplots(figsize=(10, 5.2))
    ax.set(xlim=(0, 10), ylim=(0, 5.2))
    ax.axis("off")
    boxes = [
        (
            0.2,
            3.3,
            "1  Input preparation",
            "Source hashes; nested sites\nscenario and cost contracts",
        ),
        (3.5, 3.3, "2  Routing", "OSRM + pair cache\nmaterialized workbook"),
        (
            6.8,
            3.3,
            "3  Network and preflight",
            "Nearest 20% + audited repair\npaths; model-size estimate",
        ),
        (
            6.8,
            1.0,
            "4  Native optimization",
            "Service → capacity → economics\nGurobi or SCIP/SoPlex",
        ),
        (
            3.5,
            1.0,
            "5  Independent validation",
            "Constraint and cost residuals\nincumbent + bound checks",
        ),
        (0.2, 1.0, "6  Scientific reporting", "Case/stage records\nqualified tables and figures"),
    ]
    for x, y, title, body in boxes:
        ax.add_patch(
            FancyBboxPatch(
                (x, y),
                2.95,
                1.4,
                boxstyle="round,pad=0.08",
                facecolor="#eef4f7",
                edgecolor="#345c70",
            )
        )
        ax.text(x + 1.475, y + 1.08, title, ha="center", va="center", fontsize=10, weight="bold")
        ax.text(x + 1.475, y + 0.5, body, ha="center", va="center", fontsize=9)
    for start, end in [
        ((3.17, 4), (3.4, 4)),
        ((6.47, 4), (6.7, 4)),
        ((8.28, 3.2), (8.28, 2.52)),
        ((6.7, 1.7), (6.48, 1.7)),
        ((3.4, 1.7), (3.18, 1.7)),
    ]:
        ax.add_patch(
            FancyArrowPatch(
                start, end, arrowstyle="-|>", mutation_scale=15, color="#345c70", linewidth=1.7
            )
        )
    ax.text(
        5,
        0.25,
        "Versioned inputs and evidence connect every phase; no learned module is evaluated.",
        ha="center",
        fontsize=10,
    )
    fig.savefig(destination, dpi=180, bbox_inches="tight")
    plt.close(fig)


def build(*, check: bool = False) -> None:
    source = {
        name: digest(EVIDENCE / name)
        for name in (
            "comparison_cases.json",
            "comparison_stages.json",
            "runtime_memory_comparison.png",
        )
    }
    cases = json.loads((EVIDENCE / "comparison_cases.json").read_text())
    stages = json.loads((EVIDENCE / "comparison_stages.json").read_text())
    tables = render_tables(cases, stages)
    table_path = MANUSCRIPT / "comparison_results.qmd"
    receipt_path = MANUSCRIPT / "comparison_provenance.json"
    if check:
        if table_path.read_text(encoding="utf-8") != tables:
            raise ValueError("Stale manuscript comparison tables")
        receipt = json.loads(receipt_path.read_text())
        if receipt["sources"] != source:
            raise ValueError("Changed comparison source identity")
        for name, sha in receipt["generated"].items():
            if digest(MANUSCRIPT / name) != sha:
                raise ValueError(f"Changed generated artifact: {name}")
        return
    table_path.write_text(tables, encoding="utf-8", newline="\n")
    shutil.copyfile(
        EVIDENCE / "runtime_memory_comparison.png", MANUSCRIPT / "figures/solver-comparison.png"
    )
    pipeline_figure(MANUSCRIPT / "figures/pipeline.png")
    receipt = {
        "schema_version": "manuscript-comparison-v1",
        "attempt_count": 13,
        "quality_certified_count": 4,
        "scip_incumbent_count": 0,
        "sources": source,
        "generated": {
            name: digest(MANUSCRIPT / name)
            for name in (
                "comparison_results.qmd",
                "figures/solver-comparison.png",
                "figures/pipeline.png",
            )
        },
        "scope": "frozen exported records; no new optimization or full solution revalidation",
    }
    receipt_path.write_text(json.dumps(receipt, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    build(check=parser.parse_args().check)
